image: node:8
options:
  max-time: 5
pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          name: BuildPrd
          script:
            - apt-get update -y
            - apt-get install -y zip
            - echo $INSTIMIX_PEM | base64 --decode > ~/.ssh/instimix.pem
            - chmod 700 ~/.ssh
            - chmod 600 ~/.ssh/instimix.pem
            - ssh-keyscan -H institutomix.com.br >> ~/.ssh/known_hosts
            - npm install
            - rm -rf build
            - yarn build
            - rm -rf build-bi-production.zip
            - cd build && zip -r -X "../build-bi-production.zip" * && cd ..
            - scp -i ~/.ssh/instimix.pem -r build-bi-*.zip ec2-user@institutomix.com.br:~/dev/
